version: '3.8'
services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=en_US.UTF-8 --lc-ctype=en_US.UTF-8
    env_file:
      - envs/.env.database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-postgres} -d $${POSTGRES_DB:-inextlynk}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.13
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  web:
    build: .
    command: bash -c "python manage.py migrate && gunicorn core.wsgi:application --bind 0.0.0.0:8001"
    volumes:
      - /var/www/test_project_thinkland/static:/app/staticfiles
      - /var/www/test_project_thinkland/media:/app/media
    ports:
      - "8001:8001"
    depends_on:
      - db
      - elasticsearch
    env_file:
      - envs/.env.database
      - envs/.env.django

volumes:
  postgres_data:
  esdata:
  media_data: